/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package megapoly.interfaz;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import megapoly.Jugador;

/**
 *
 * @author jjesu
 */
public class NuevaPartida extends javax.swing.JFrame {

    private Jugador jugador1;
    private Jugador jugador2;
    private Jugador jugador3;
    private Jugador jugador4;

    /**
     * Creates new form NuevaPartida
     */
    public NuevaPartida() {
        initComponents();
        nombrej1.setVisible(false);
        nombrej2.setVisible(false);
        nombrej3.setVisible(false);
        nombrej4.setVisible(false);
        jugador1 = null;
        jugador2 = null;
        jugador3 = null;
        jugador4 = null;
    }

    public Jugador getJugador1() {
        return jugador1;
    }

    public void setJugador1(Jugador jugador1) {
        this.jugador1 = jugador1;
    }

    public Jugador getJugador2() {
        return jugador2;
    }

    public void setJugador2(Jugador jugador2) {
        this.jugador2 = jugador2;
    }

    public Jugador getJugador3() {
        return jugador3;
    }

    public void setJugador3(Jugador jugador3) {
        this.jugador3 = jugador3;
    }

    public Jugador getJugador4() {
        return jugador4;
    }

    public void setJugador4(Jugador jugador4) {
        this.jugador4 = jugador4;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbNumeroJugadores = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        nombrej1 = new javax.swing.JTextField();
        nombrej2 = new javax.swing.JTextField();
        nombrej3 = new javax.swing.JTextField();
        nombrej4 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lNumeroJugadores = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bComenzarPartida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(817, 561));

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 205));

        cbNumeroJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Numero de jugadores", "2 Jugadores", "3 Jugadores", "4 Jugadores", " " }));
        cbNumeroJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNumeroJugadoresActionPerformed(evt);
            }
        });

        jPanel5.setLayout(new java.awt.GridLayout(0, 1));

        nombrej1.setText("Nombre Jugador 1");
        nombrej1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrej1ActionPerformed(evt);
            }
        });
        jPanel5.add(nombrej1);

        nombrej2.setText("Nombre Jugador 2");
        jPanel5.add(nombrej2);

        nombrej3.setText("Nombre Jugador 3");
        jPanel5.add(nombrej3);

        nombrej4.setText("Nombre Jugador 4");
        nombrej4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrej4ActionPerformed(evt);
            }
        });
        jPanel5.add(nombrej4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cbNumeroJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(cbNumeroJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setForeground(new java.awt.Color(51, 0, 51));

        lNumeroJugadores.setForeground(new java.awt.Color(51, 51, 0));
        lNumeroJugadores.setText("Selecciona el número de jugadores");
        jPanel3.add(lNumeroJugadores);

        bComenzarPartida.setText("Comenzar");
        bComenzarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComenzarPartidaActionPerformed(evt);
            }
        });
        jPanel4.add(bComenzarPartida);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * 
     * @param evt 
     */
    private void bComenzarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComenzarPartidaActionPerformed
        // TODO add your handling code here:
        Dimension dim;
        dim = super.getToolkit().getScreenSize();
        if (cbNumeroJugadores.getSelectedItem().toString().equalsIgnoreCase("2 Jugadores")) {
            VentanaPartida partida = new VentanaPartida(jugador1, jugador2);
            partida.setSize(dim);
            partida.setVisible(true);
        } else if (cbNumeroJugadores.getSelectedItem().toString().equalsIgnoreCase("3 Jugadores")) {
            VentanaPartida partida = new VentanaPartida(jugador1, jugador2, jugador3);
            partida.setSize(dim);
            partida.setVisible(true);
        } else if (cbNumeroJugadores.getSelectedItem().toString().equalsIgnoreCase("4 Jugadores")) {
            VentanaPartida partida = new VentanaPartida(jugador1, jugador2, jugador3, jugador4);
            partida.setSize(dim);
            partida.setVisible(true);
        }


    }//GEN-LAST:event_bComenzarPartidaActionPerformed
    /**
     * 
     * @param evt 
     */
    private void cbNumeroJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNumeroJugadoresActionPerformed
        // TODO add your handling code here:

        if (cbNumeroJugadores.getSelectedItem().toString().equalsIgnoreCase("2 Jugadores")) {
            

            nombrej1.setText(JOptionPane.showInputDialog(null, "Nombre", "Nombre del jugador 1", 1));
            nombrej2.setText(JOptionPane.showInputDialog(null, "Nombre", "Nombre del jugador 2", 1));
            
            nombrej1.setVisible(true);
            nombrej2.setVisible(true);

            jugador1 = new Jugador(nombrej1.getText());
            jugador2 = new Jugador(nombrej2.getText());

        } else if (cbNumeroJugadores.getSelectedItem().toString().equalsIgnoreCase("3 Jugadores")) {
            nombrej1.setVisible(true);
            nombrej2.setVisible(true);
            nombrej3.setVisible(true);

            nombrej1.setText(JOptionPane.showInputDialog(null, "Nombre", "Nombre del jugador 1", 1));
            nombrej2.setText(JOptionPane.showInputDialog(null, "Nombre", "Nombre del jugador 2", 1));
            nombrej3.setText(JOptionPane.showInputDialog(null, "Nombre", "Nombre del jugador 3", 1));

            jugador1 = new Jugador(nombrej1.getText());
            jugador2 = new Jugador(nombrej2.getText());
            jugador3 = new Jugador(nombrej3.getText());
        } else if (cbNumeroJugadores.getSelectedItem().toString().equalsIgnoreCase("4 Jugadores")) {
            nombrej1.setVisible(true);
            nombrej2.setVisible(true);
            nombrej3.setVisible(true);
            nombrej4.setVisible(true);

            nombrej1.setText(JOptionPane.showInputDialog(null, "Nombre", "Nombre del jugador 1", 1));
            nombrej2.setText(JOptionPane.showInputDialog(null, "Nombre", "Nombre del jugador 2", 1));
            nombrej3.setText(JOptionPane.showInputDialog(null, "Nombre", "Nombre del jugador 3", 1));
            nombrej4.setText(JOptionPane.showInputDialog(null, "Nombre", "Nombre del jugador 4", 1));

            jugador1 = new Jugador(nombrej1.getText());
            jugador2 = new Jugador(nombrej2.getText());
            jugador3 = new Jugador(nombrej3.getText());
            jugador4 = new Jugador(nombrej4.getText());
        }
    }//GEN-LAST:event_cbNumeroJugadoresActionPerformed

    private void nombrej4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrej4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrej4ActionPerformed

    private void nombrej1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrej1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrej1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bComenzarPartida;
    private javax.swing.JComboBox<String> cbNumeroJugadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lNumeroJugadores;
    private javax.swing.JTextField nombrej1;
    private javax.swing.JTextField nombrej2;
    private javax.swing.JTextField nombrej3;
    private javax.swing.JTextField nombrej4;
    // End of variables declaration//GEN-END:variables
}
